### ISSUE TITLE
Uglify JavaScript during build process

### ISSUE THREAD

**Issue by kwhinnery** [kwhinnery/todomvc-plusplus#3]
When we build static assets for production, we currently minify CSS but don't compress our javascript. We should uglify our JavaScript using Grunt, and add that to the `collect_static` task.

**Comment by maurop123** [comment]
Do you want to _not_ include sourcemaps?

**Comment by kwhinnery** [comment]
Not in the uglified version, as the intent here is to use this asset in production. If it was included, it would need to be external rather than inline in a comment.

**Comment by kwhinnery** [comment]
Not including sourcemaps at all would be fine.

**Comment by bganicky** [comment]
I don't know how to do a pull request when I already made one in the second issue and am now a one commit ahead. :) Is there a way do that?

**Comment by maurop123** [comment]
https://github.com/kwhinnery/todomvc-plusplus/pull/24

Solved with src and dest and app.min.js
