### ISSUE TITLE
Add an npm script as a shortcut for the Sequelize migrate command

### ISSUE THREAD

**Issue by kwhinnery** [kwhinnery/todomvc-plusplus#5]
In case someone doesn't have the Sequelize CLI installed globally, it would be nice to be able to at least execute the migrations for the app without installing `sequelize-cli` globally. Create an npm script that accomplishes this task. Then, create a Grunt shell command which executes this script.

There might be something there already that does this as part of the startup process, but let's make a special purpose npm script.

**Comment by JamesMGreene** [comment]
@bganicky Looks like there is another part of this issue that your PR has not addressed yet:

> Then, create a Grunt shell command which executes this script.

**Comment by JamesMGreene** [comment]
@bganicky Actually, your PR does not accomplish this part of the issue either:

> In case someone doesn't have the Sequelize CLI installed globally, it would be nice to be able to at least execute the migrations for the app without installing `sequelize-cli` globally.

:confused:

**Comment by anthonybrown** [comment]
did this get fixed, I had to run an errand

**Comment by bganicky** [comment]
@JamesMGreene  Forgot about the Grunt task, but the second concern should be ok because if you run "sequelize" from npm script, it should use the project's one in "node_modules/bin" instead the global one. But I messed upped the pull requests anyway. :)
