### ISSUE TITLE
Add X-Shenanigans-None to all API responses

### ISSUE THREAD

**Issue by kwhinnery** [kwhinnery/todomvc-plusplus#7]
A storied Twilio tradition is adding the `X-Shenanigans: None` header to every HTTP response we send. Create an Express middleware to do this, but only for `/todos` routes.

**Comment by DWboutin** [comment]
I was having a git issue, so there's the middleware for that ^^

```
app.use('/todos', (request, response, next) => {
  response.set({
    'X-Shenanigans-None': 'true'
  });
  next();
});
```

**Comment by jeremyroe** [comment]
My fix was done as follows in todos.js

`/ Fetch all TODOs
exports.all = (request, response) => {
  response.setHeader("X-Shenanigans", "none");
  Todo.findAll({
    limit: 1000,
    order: [ ['createdAt', 'ASC'] ]
  }).then((todos) => {
    response.send(todos);
  }).catch((error) => {
    response.status(500).send(error);
  });`
