### ISSUE TITLE
init_static not working when running grunt

### ISSUE THREAD

**Issue by pertrai1** [kwhinnery/todomvc-plusplus#8]
I have tried to run grunt to build from the README and I get an error that `init_static` is not a task

```
grunt.registerTask('collect_static', 
    ['init_static', 'sass:dist', 'browserify']);
```

Was this fixed before I joined or am I missing something?

**Comment by kwhinnery** [comment]
The actual task, as you see here, is `grunt collect_static` - I will double check that the README has the right value.

**Comment by pertrai1** [comment]
@kwhinnery 

```
Warning: Task "init_static" not found. Use --force to continue.
```

**Comment by pertrai1** [comment]
I get this before that error:

`SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`

**Comment by kwhinnery** [comment]
That is the error you'll get if not using Node 6+ - would recommend upgrading to latest current or using [nvm](https://github.com/creationix/nvm) to get a later version.

**Comment by pertrai1** [comment]
Thank you
