### ISSUE TITLE
 SequelizeConnectionError: read ECONNRESET

### ISSUE THREAD

**Issue by mayank13** [kwhinnery/todomvc-plusplus#9]
Getting this issue while running the migrate command on Windows
Unable to connect to database: SequelizeConnectionError: password authentication failed for user "XXXXX"

**Comment by kwhinnery** [comment]
We'll look at this in chat if you're still having troubles?

**Comment by kinsomicrote** [comment]
Hello, please I am having this issue on Ubuntu. How do I resolve it?
